
import { Metadata } from 'next';
import PageWalk from '../../../ui/organisms/pageWalk/pageWalk';

export const metadata: Metadata = {
  title: 'Toutes les balades',
  description: 'Generated by create next app',
}

export default function Balades() {

  return (
    <main className='font-sans'>
      <PageWalk />
    </main>
  );
}