import Banner from '../ui/atoms/banner/banner';
import ContentNavigation from '../ui/molecules/contentNavigation/contentNavigation';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Dogs are awesome',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className={inter.className}>
        <ContentNavigation />
        <Banner />
        {children}
      </body>
    </html>
  );
}
