import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Balade',
  description: 'Generated by create next app',
}

export default function Page({ params }: { params: { slug: string } }) {
  return <h1>My Page</h1>
}